name: main retrain model

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: retrain_env
        environment-file: MLProject/conda.yaml
        auto-activate-base: false

    - name: Install MLflow
      run: |
        pip install mlflow

    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run . --env-manager=local
        
    - name: Install Git LFS
      run: |
        sudo apt-get update && sudo apt-get install -y git-lfs
        git lfs install

    - name: Copy artifact model to saved_model
      run: |
        mkdir -p MLProject/saved_model
        cp MLProject/random_forest_model.pkl MLProject/saved_model/

    - name: Commit artifact ke github (LFS)
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Github Action"
        git config --global user.email "actions@github.com"

        git lfs track "MLProject/saved_model/random_forest_model.pkl"
        git add .gitattributes
        git add MLProject/saved_model/random_forest_model.pkl || true
        git diff --cached --quiet || git commit -m "add retrained model artifact (LFS)"

        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git push origin HEAD:${{ github.ref_name }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/msml_popo_zakaria:latest .
      
    - name: Login to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/msml_popo_zakaria:latest
